### ISSUE TITLE
Inliners, outliners

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [srinath1905/GRANSAC#3] opened 2018-04-12 09:27 UTC
<img width="361" alt="2018-04-12 12 20 03" src="https://user-images.githubusercontent.com/964601/38668124-125dc83a-3e4c-11e8-89b7-8dec0f8f6a41.png">
On your screenshot the black dot also visible near line below green one. Maybe there some error in code.
In my opinion simple example without generic types may have more profit for understanding and usage. There much more code in model, that in `GRANSAC.h`. It's not bad, but start thinking do we really need this abstraction with templates.

**Comment by drsrinathsridhar** [comment] 2018-04-13 20:37
Closing this as a duplicate of #4

**Closed as completed by drsrinathsridhar** 2018-04-13 20:37 UTC
